export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const OFFERS_ROUTE = '/'
export const ACCOUNT_ROUTE = '/account'
export const TOUR_ROUTE = '/tour'